[build.environment]
NPM_FLAGS = "--version"
NODE_VERSION = "16"

[build]
publish = "docs/.vitepress/dist"
command = "npx pnpm i --store=node_modules/.pnpm-store && npm run docs:build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
