[build.environment]
NPM_FLAGS = "--version"
NODE_VERSION = "18.16.1"

[build]
base = "docs-zh/"
publish = ".vitepress/dist"
command = "npx pnpm i --store=node_modules/.pnpm-store && npm run build:zh"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
