name: sync doc file with envd

on: [repository_dispatch, workflow_dispatch]


jobs:
  sync_file:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout Envd-docs
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: envd-docs
      - name: Checkout Envd
        uses: actions/checkout@v3
        with:
          repository: 'tensorchord/envd'
          fetch-depth: 0
          path: envd
      - run: |
          ls .
          ls ..
      - run: |
          mkdir -p envd-docs/hack/api/api/
          cp envd/envd/api/* envd-docs/hack/api/api/
          cd envd-docs/
          git add hack/api/api
          git commit -m "sync with main repo"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
