name: sync doc file with envd

on: [repository_dispatch, workflow_dispatch]

jobs:
  sync_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Checkout Envd-docs
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: envd-docs
      - name: Checkout Envd
        uses: actions/checkout@v3
        with:
          repository: 'tensorchord/envd'
          fetch-depth: 0
          path: envd
      - run: |
          mkdir -p envd-docs/hack/api/api/
          cp envd/envd/api/* envd-docs/hack/api/api/      
      - name: Generate markdown docs
        run: |
          python -m pip install -r hack/api/requirement.txt
          make generate-api-ref
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          path: envd-docs
          add-paths: hack/api
          branch: sync_envd
          title: Auto sync doc with envd repo
        